name: ProgressPlugin
version: '${project.version}'
main: de.minefactprogress.progressplugin.Main
api-version: 1.18
website: https://progress.minefact.de
depend:
  - HeadDatabase
commands:
  district:
    usage: <show|hide|toggle|info>
  progress:
    usage: /progress
  bc:
    usage: /bc
  noclip:
    usage: /noclip
    aliases: [nc]
  locationeditor:
    usage: /locationeditor
    aliases: [le]
  /side:
    usage: //side
